forum/urls.py
from django.urls import path
from forum.views import *
from timeline.views import delete, upvote, upvote_ajax, comment, add_comment, comment_json

app_name = 'forum'

urlpatterns = [
    path('json/', show_json, name='json'),
    path('group/<str:group_name>/json/', show_json_group, name='json_group'),
    path('create-post/', create_post, name='create-post'),
    path('create-forum/', create_group, name='create-group'),
    path('create-forum/name/', get_group_name, name='group-name'),
    path('mypost/', show_my_post, name='my-post'),
    path('mypost/json/', show_my_post_json, name="my-post-json"),
    path('mypost/<int:content_id>/delete/', delete_post, name='delete'),
    path('mypost/<int:content_id>/upvote/', upvote_ajax, name='mypost-upvote'),
    path('mypost/<int:content_id>/comment/', comment, name='mypost-comment'),
    path('mypost/<int:content_id>/comment/json/', comment_json, name='mypost-comment'),
    path('mypost/<int:content_id>/comment/add/', add_comment, name='mypost-comment'),
    path('mypost/<int:content_id>/edit/', edit_post, name='mypost-edit'),
    
    path('mypost/<int:content_id>/edit/flutter/', edit_post_flutter, name='mypost-edit-flutter'),
    path('create-post-flutter/', create_post_flutter, name='create-post-flutter'),
    path('create-forum-flutter/', create_group_flutter, name='create-group-flutter'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('timeline.urls')),
    path('', include('authen.urls')),
    path('', include('forum.urls')),
    path('', include('profile_page.urls')),
    path('hall/', include('hall_of_shame.urls')),
    path('auth/', include('authentication.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authen/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.png", null=True, blank=True)
    alias = models.CharField(max_length=255, default="Anonymous") # Beda sama username, bisa diganti gitu
    # TODO Mau ada field apa lagi?
    is_admin = models.BooleanField(default=False)
 
class Content(models.Model):
    creator = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_captured = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_captured = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField()
    upvote_count = models.PositiveIntegerField(default=0)
    
    def get_creator_name(self):
        return self.creator.alias

class ContentUpvote(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE)
    upvoter = models.ManyToManyField(UserProfile)
    
    def get_upvote(self):
        return self.upvoter.distinct().count()
    

forum/forms.py
from django import forms
from authen.models import Content
from forum.models import Forum
import re

class TaskForms(forms.ModelForm):
    name_list = list(Forum.objects.values_list('title'))
    pk_list = list(Forum.objects.values_list('pk'))
    temp = []
    for i in range(len(name_list)):
        temp.append(tuple([pk_list[i][0], name_list[i][0]]))
    forum_option = tuple(temp)
    group = forms.MultipleChoiceField(choices=forum_option)
    class Meta:
        model = Content
        fields = [
            'title',
            'description',
        ]

class ForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = [
            'title',
            'description',
        ]
    
    def clean_title(self):
        data = self.cleaned_data
        if not ('title' in data.keys()):
            raise forms.ValidationError(("Please fill out missing fields."))

        title = data['title']
        
        regex = "^[A-Za-z0-9._~-]*$"
        if not (bool(re.match(regex, title))):
            raise forms.ValidationError("Nama tidak valid")
        
        return title
        
        

forum/views.py
from django.shortcuts import render
from authen.models import UserProfile, Content, ContentUpvote
from forum.models import Forum, Members
from forum.forms import TaskForms, ForumForm
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core import serializers
import json
from django.views.decorators.csrf import csrf_exempt
from django.utils.timezone import make_aware
import datetime
# Create your views here.


@login_required(login_url='/login/')
def create_post(request):
    form = TaskForms(request.POST)
    response_data = {}
    if request.method == 'POST':
        print(request.POST.get("group"))
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            forum_id = form.cleaned_data['group']
            print(forum_id)
            seller = request.user.userprofile
            content_baru = Content.objects.create(
                creator=seller, title=title, description=description)
            ContentUpvote.objects.create(content=content_baru)
            for pk in forum_id:
                forum = Forum.objects.get(id=pk)
                forum.contents.add(content_baru)
            return redirect('timeline:landing')

        else:
            messages.info(request, 'Input anda tidak valid')
    response_data['form'] = form
    response_data['forums'] = Forum.objects.all()
    return render(request, "create_post.html", response_data)


@csrf_exempt
@login_required(login_url='/login/')
def create_post_flutter(request):
    form = TaskForms(request.POST)
    response_data = {}
    if request.method == 'POST':
        title = request.POST.get("title")
        description = request.POST.get("description")

        group = request.POST.get("group")
        list_of_char = ["[", "]", ","]
        # Create a mapping table to map the characters
        # to be deleted with empty string
        translation_table = str.maketrans('', '', ''.join(list_of_char))
        group = group.translate(translation_table)
        group = group.split(" ")
        forum_id = [int(i) for i in group]

        seller = request.user.userprofile
        content_baru = Content.objects.create(
            creator=seller, title=title, description=description)
        ContentUpvote.objects.create(content=content_baru)
        for pk in forum_id:
            forum = Forum.objects.get(id=pk)
            forum.contents.add(content_baru)
        return JsonResponse({"status": "oke"})
    response_data['form'] = form
    response_data['forums'] = Forum.objects.all()
    print("Masuk 3")
    return JsonResponse({"status": "gagal"})


@login_required(login_url='/login/')
def create_group(request):
    form = ForumForm(request.POST)
    response_data = {}
    if request.method == 'POST' and form.is_valid():
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        creator = request.user.userprofile
        new_forum = Forum.objects.create(
            creator=creator, title=title, description=description)
        members = Members.objects.create(forum=new_forum)
        members.subscriptor.add(creator)
        # TODO Nanti ini ganti ke landing page utama
        return redirect('timeline:landing')

    response_data['form'] = form
    return render(request, "create_group.html", response_data)


@csrf_exempt
@login_required(login_url='/login/')
def create_group_flutter(request):
    form = ForumForm(request.POST)
    response_data = {}
    if request.method == 'POST' and form.is_valid():
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        creator = request.user.userprofile
        new_forum = Forum.objects.create(
            creator=creator, title=title, description=description)
        members = Members.objects.create(forum=new_forum)
        members.subscriptor.add(creator)
        # TODO Nanti ini ganti ke landing page utama
        return JsonResponse({"status": "oke"})

    return JsonResponse({"status": "gagal"})


@login_required(login_url='/login/')
def show_json(request):
    response_data = {}
    content = Content.objects.filter(creator=request.user.userprofile)
    response_data["user"] = json.loads(
        serializers.serialize("json", [request.user.userprofile]))
    response_data['data'] = json.loads(serializers.serialize("json", content))
    return JsonResponse((response_data))

# @login_required(login_url='/login/')


def show_json_group(request, group_name):
    response_data = {}
    forum = Forum.objects.get(title=group_name)
    content = forum.contents.all()
    member = forum.members.subscriptor.all()
    """
    var nameMap = {};
    for (int i = 0; i < data.member.length; i++){
        nameMap[data.member[i].pk] = data.member[i].fields.alias
    }
    """
    response_data['forum'] = json.loads(serializers.serialize("json", [forum]))
    response_data['content'] = json.loads(
        serializers.serialize("json", content))
    return JsonResponse(response_data)


@login_required(login_url='/login/')
def get_group_name(request):
    group_name = Forum.objects.values_list('title')
    return JsonResponse({'name_list': list(group_name)})


@login_required(login_url='/login/')
def show_my_post(request):
    user_name = request.user.username
    data = Content.objects.filter(creator=request.user.userprofile)
    context = {
        'list_forum': data,
        'user_name': user_name,
    }
    return render(request, "my-post.html", context)

# TODO Jadiin login required


@login_required(login_url='/login/')
def show_my_post_json(request):
    content = Content.objects.filter(creator=request.user.userprofile)
    return HttpResponse(serializers.serialize("json", content), content_type="application/json")


@csrf_exempt
@login_required(login_url='/login/')
def edit_post(request, content_id):
    form = TaskForms(request.POST)
    response_data = {}
    nama = request.POST.get('name')
    description = request.POST.get('description')
    if request.method == 'POST' and nama != '' and description != '':
        id = request.POST.get('id')
        post = Content.objects.get(id=id)
        if request.POST.get('is_captured') == "true":
            if (request.POST.get('date_captured') != ''):
                # TODO Edit isi dari post-nya
                post.title = nama
                post.description = description
                post.is_captured = True
                date = request.POST.get('date_captured')
                post.date_captured = date
                post.save()
                response_data['msg'] = "success"
                response_data['title'] = nama
                response_data['id'] = id
                response_data['description'] = description
                response_data['is_captured'] = True
                response_data['date_captured'] = date
                response_data['date_created'] = post.date_created
                response_data['upvote_count'] = post.upvote_count
                response_data['creator_id'] = request.user.userprofile.id
                return JsonResponse(response_data)
        else:
            # TODO edit isi dari post-nya
            post.title = nama
            post.description = description
            post.is_captured = False
            post.save()
            response_data['msg'] = "success"
            response_data['title'] = nama
            response_data['id'] = id
            response_data['description'] = description
            response_data['is_captured'] = False
            response_data['date_created'] = post.date_created
            response_data['upvote_count'] = post.upvote_count
            response_data['msg'] = "success"
            response_data['creator_id'] = request.user.userprofile.id
            return JsonResponse(response_data)
    response_data['msg'] = "fail"
    return JsonResponse(response_data)

@csrf_exempt
@login_required(login_url='/login/')
def edit_post_flutter(request, content_id):
    form = TaskForms(request.POST)
    response_data = {}
    nama = request.POST.get('name')
    description = request.POST.get('description')
    if request.method == 'POST' and nama != '' and description != '':
        id = request.POST.get('id')
        post = Content.objects.get(id=id)
        if request.POST.get('is_captured') == "true":
            if (request.POST.get('date_captured') != ''):
                # TODO Edit isi dari post-nya
                post.title = nama
                post.description = description
                post.is_captured = True
                date = request.POST.get('date_captured')
                try:
                    date_fix = datetime.datetime.strptime(
                        date, "%Y-%m-%dT%H:%M:%SZ")
                except:
                    date_fix = datetime.datetime.strptime(
                        date, "%Y-%m-%d %H:%M:%S.%f")
                date_fix = make_aware(date_fix)
                post.date_captured = date_fix
                post.save()
                response_data['msg'] = "success"
                response_data['title'] = nama
                response_data['id'] = id
                response_data['description'] = description
                response_data['is_captured'] = True
                response_data['date_captured'] = date
                response_data['date_created'] = post.date_created
                response_data['upvote_count'] = post.upvote_count
                response_data['creator_id'] = request.user.userprofile.id
                return JsonResponse(response_data)
        else:
            # TODO edit isi dari post-nya
            post.title = nama

forum/templates/create_group.html
{% extends 'base-with-header.html' %}

{% block meta %}
<title>Create Forum</title>
{% load static %}
<script src="{% static 'js/createGroup.js' %}" type="text/javascript"></script>

{% endblock meta %}

{% block content %}
<div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
    <form class="needs-validation" method="POST" action="" novalidate>
        {% csrf_token %}
        <div class="row">
            <h1 style="text-align:center">Create Forum</h1>
        </div>
        <div class="row top-buffer">
            <div class="col-xl-2 align-self-center">
                <label class="form-lable" for="id_forum_name">Forum Name</label>
            </div>
            <div class="col align-self-center">
                <input type="text" name="title" placeholder="Nama Forumnya" id="id_forum_name" class="form-control"
                    pattern="^[A-Za-z0-9._~-]*$" required>
                <div class="invalid-feedback" id="feedback-url">
                    Masukkan nama forum yang sesuai (hanya alphanumeric (case sensitive), ".", "_", "~", dan "-").
                </div>
                <div class="invalid-feedback" id="feedback-exist">
                    Sudah ada forum dengan nama itu.
                </div>
            </div>
        </div>
        <div class="row top-buffer">
            <div class="col-xl-2 align-self-center">
                <label class="form-lable" for="id_description">Description</label>
            </div>
            <div class="col align-self-center">
                <input type="text" name="description" placeholder="Jelaskan isi dari forum" id="id_description"
                    class="form-control" required>
                <div class="invalid-feedback">
                    Masukkan deskripsi dari forum.
                </div>
            </div>
        </div>
        <input type="submit" name="submit" value="Create" class="btn btn-custom mx-auto d-block top-buffer">
    </form>
</div>

{% endblock content %}

forum/templates/create_post.html
{% extends 'base-with-header.html' %}

{% block meta %}
<title>Create Post</title>
{% load static %}
{% endblock meta %}

{% block content %}
<div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
    <form class="needs-validation" method="POST" action="" novalidate>
        {% csrf_token %}
        <div class="row">
            <h1 style="text-align:center">Create Post</h1>
        </div>
        <div class="row top-buffer">
            <div class="col-xl-2 align-self-center">
                <label class="form-lable" for="id_title">Name</label>
            </div>
            <div class="col align-self-center">
                <input type="text" name="title" placeholder="Nama Penjahat" id="id_title" class="form-control" required>
                <div class="invalid-feedback">
                    Masukkan Nama Yang Sesuai.
                  </div>
            </div>
        </div>
        <div class="row top-buffer">
            <div class="col-xl-2 align-self-center">
                <label class="form-lable" for="id_description">Description</label>
            </div>
            <div class="col align-self-center">
                <input type="text" name="description" placeholder="Jelaskan Kejahatannya" id="id_description"
                    class="form-control" required>
                    <div class="invalid-feedback">
                        Masukkan penjelasan Kejahatannya.
                      </div>
            </div>
        </div>
        <div class="row top-buffer">
            <div class="col-xl-2 align-self-center">
                <label class="form-lable" for="id_group">Group Forum</label>
            </div>
            <div class="col align-self-center">
                <select name="group" id="id_group" class="form-select multiple-select" data-placeholder="Masukkan forum tempat post" required multiple>
                    {% for forum in forums %}
                    <option value="{{forum.id}}">{{forum.title}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <input type="submit" name="submit" value="Create" class="btn btn-custom mx-auto d-block top-buffer">
    </form>
</div>
{% endblock content %}

forum/templates/my-post.html
{% extends 'base-with-header.html' %}

{% block meta %}
{% load static %}
<title>My Post</title>
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock meta %}

{% block content %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Post</title>
    <style>
        label, h2 {
            color: black;
        }
    </style>
</head>

<body>
    <script src="{% static 'js/myPost.js' %}" type="text/javascript"></script>
    <h1>My Post</h1>
    <h3>Halo {{user_name}}</h3>

    <div id="my-post" class="row justify-content-center" style="margin-inline:100px; margin-top:50px;">
    </div>
    <div class="modal fade" id="modalTambahTask" tabindex="-1" aria-labelledby="modalTambahTaskLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title fs-5" id="modalTambahTaskLabel">Edit Post</h2>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
                        onclick="resetForm();"></button>
                </div>
                <div class="modal-body">
                    <form class="needs-validation" method="POST" action="" id="form-edit-post" style="width:auto;"
                        novalidate>
                        {% csrf_token %}
                        <div class="row top-buffer">
                            <div class="col-xl-3 align-self-center">
                                <label class="form-lable" for="id_title">Name </label>
                            </div>
                            <div class="col align-self-center">
                                <input type="text" name="title" placeholder="Nama Penjahat" id="id_title"
                                    class="form-control" required>
                                <div class="invalid-feedback">
                                    Masukkan Nama Yang Sesuai.
                                </div>
                            </div>
                        </div>
                        <div class="row top-buffer">
                            <div class="col-xl-3 align-self-center">
                                <label class="form-lable" for="id_description">Description</label>
                            </div>
                            <div class="col align-self-center">
                                <input type="text" name="description" placeholder="Jelaskan Kejahatannya"
                                    id="id_description" class="form-control" required>
                                <div class="invalid-feedback">
                                    Masukkan penjelasan Kejahatannya.
                                </div>
                            </div>
                        </div>
                        <div class="row top-buffer">
                            <div class="col-xl-3 align-self-center">
                                <label class="form-lable" for="id_checkbox">Tertangkap?</label>
                            </div>
                            <div class="col align-self-center">
                                <input value="Tertangkap" type="checkbox" name="is_captured" id="id_checkbox"
                                    onclick="$('#input-date').toggleClass('d-none');">
                                <div class="invalid-feedback">
                                    Masukkan penjelasan Kejahatannya.
                                </div>
                            </div>
                        </div>
                        <div class="row top-buffer d-none" id="input-date">
                            <div class="col-xl-3 align-self-center">
                                <label class="form-lable" for="id_capture_date">Tanggal Ditangkap</label>
                            </div>
                            <div class="col align-self-center">
                                <input type="date" name="date_captured" id="id_capture_date" class="form-control"
                                    required>
                                <div class="invalid-feedback">
                                    Masukkan Tanggal ditangkapnya
                                </div>
                            </div>
                        </div>
                        <input type="hidden" value="2" id="id_id_post">
                </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                        onclick="resetForm();">Close</button>
                    <input type="submit" name="submit" id="addButton" value="Tambah" class="btn btn-primary"
                        onclick="editPost();">
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock content %}