authentication/urls.py
from django.urls import path
from authentication.views import login, register, logout

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='json'),
    path('register/', register, name='signup'),
    path('logout/', logout, name='logout'),
]

forum/urls.py
from django.urls import path
from forum.views import *
from timeline.views import delete, upvote, upvote_ajax, comment, add_comment, comment_json

app_name = 'forum'

urlpatterns = [
    path('json/', show_json, name='json'),
    path('group/<str:group_name>/json/', show_json_group, name='json_group'),
    path('create-post/', create_post, name='create-post'),
    path('create-forum/', create_group, name='create-group'),
    path('create-forum/name/', get_group_name, name='group-name'),
    path('mypost/', show_my_post, name='my-post'),
    path('mypost/json/', show_my_post_json, name="my-post-json"),
    path('mypost/<int:content_id>/delete/', delete_post, name='delete'),
    path('mypost/<int:content_id>/upvote/', upvote_ajax, name='mypost-upvote'),
    path('mypost/<int:content_id>/comment/', comment, name='mypost-comment'),
    path('mypost/<int:content_id>/comment/json/', comment_json, name='mypost-comment'),
    path('mypost/<int:content_id>/comment/add/', add_comment, name='mypost-comment'),
    path('mypost/<int:content_id>/edit/', edit_post, name='mypost-edit'),
    
    path('mypost/<int:content_id>/edit/flutter/', edit_post_flutter, name='mypost-edit-flutter'),
    path('create-post-flutter/', create_post_flutter, name='create-post-flutter'),
    path('create-forum-flutter/', create_group_flutter, name='create-group-flutter'),
]

hall_of_shame/urls.py
from django.urls import path
from hall_of_shame.views import (
    show_hall_of_shame,
    get_hall_of_shame,
    add_corruptor,
    delete_corruptor,
    show_detail,
    add_corruptor_flutter,
    delete_flutter,
)

app_name = 'hall_of_shame'

urlpatterns = [
    path('', show_hall_of_shame, name='show_hall_of_shame'),
    path('json/', get_hall_of_shame, name='get_hall_of_shame'),
    path('add/', add_corruptor, name='add_corruptor'),
    path('delete/<id>/', delete_corruptor, name='delete_corruptor'),
    path('detail/<id>/', show_detail, name='show_detail'),
    path('add-flutter/', add_corruptor_flutter, name='add_corruptor_flutter'),
    path('delete-flutter/<id>/', delete_flutter, name='delete_flutter'),
]

profile_page/urls.py
from django.urls import path
from profile_page.views import *

app_name = 'profile_page'

urlpatterns = [
    path('myprofile/', show_my_profile, name='my-profile'),
    path('myprofile/json', get_my_profile_json, name='get_my_profile_json'),
    path('myprofile/edit', edit_my_profile, name="edit-my-profile"),
    path('myprofile/edit-flutter', edit_my_profile_flutter, name="edit-my-profile-flutter")
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('timeline.urls')),
    path('', include('authen.urls')),
    path('', include('forum.urls')),
    path('', include('profile_page.urls')),
    path('hall/', include('hall_of_shame.urls')),
    path('auth/', include('authentication.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timeline/urls.py
from django.urls import path
from timeline.views import *

app_name = 'timeline'

urlpatterns = [
    path('group/<str:group_name>/', show_timeline, name='timeline'),
    path('group/<str:group_name>/<int:content_id>/comment/', comment, name='comment'),
    path('group/<str:group_name>/<int:content_id>/comment/json/', comment_json, name='comment'),
    path('group/<str:group_name>/<int:content_id>/comment/add/', add_comment, name='comment'),
    path('', show_group, name='landing'),
    path('group/<str:group_name>/<int:content_id>/delete/', delete, name='delete'),
    path('group/<str:group_name>/<int:content_id>/upvote/', upvote, name='upvote'),
    path('show-group-json/', show_group_json, name="show-group-json"),
    
    path('group/<str:group_name>/json-flutter/', show_timeline_json, name='timeline'),
]

templates/base-with-header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"
        type="text/javascript"></script>

    <script src="{% static 'js/test.js' %}" type="text/javascript"></script>
    <div class="overlay"></div>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <script src="{% static 'js/sidebar.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    {% block meta %}
    {% endblock meta %}
</head>

<body>
    <style>

        #sidebarCollapse:hover{
            background: #DA0037;
            color: #2C3333;
            border-color:#2C3333;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <header class="p-3 mb-3 border-bottom sticky-top" id="header">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                        <use xlink:href="#bootstrap" />
                    </svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <button type="button" id="sidebarCollapse" class="btn btn-custom-header">
                        <i class="fas fa-align-left"></i>
                        <span>Menu</span>
                    </button>
                </ul>

                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        {% if user_name == "AnonymousUser" %}
                        <img src="/images/default.png" alt="mdo" width="35" height="35"
                                class="rounded-circle">
                        {% else %}
                        <img src="{{ request.user.userprofile.image.url }}" alt="mdo" width="35" height="35"
                            class="rounded-circle">
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li><a class="dropdown-item" href="{% url 'profile_page:my-profile' %}">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'forum:my-post' %}">My Post</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'authen:logout' %}">Sign out</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <!-- Sidebar  -->
    <nav id="sidebar">
        <div id="dismiss">
            <i class="bi bi-x-lg"></i>
        </div>

        <div class="sidebar-header">
            <h4>Whistle Blower</h4>
        </div>

        <ul class="list-unstyled components">
            <li>
                <a href="{% url 'timeline:landing' %}">Homepage</a>
            </li>
            <li>
                <a href="{% url 'hall_of_shame:show_hall_of_shame' %}">Hall of Shame</a>
            </li>
        </ul>

        <ul class="list-unstyled CTAs">
            <li class="top-buffer">
                <a href="{% url 'forum:create-group' %}" class="download top-buffer">Create Forum</a>
            </li>
            <li class="top-buffer">
                <a href="{% url 'forum:create-post' %}" class="article top-buffer">Create Post</a>
            </li>
        </ul>
    </nav>

    {% block content %}
    {% endblock content %}
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" type="text/javascript"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>